version: '3'

services:
  sample:
    container_name: damdamn
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development